# Generated by Django 4.1.5 on 2023-02-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(db_index=True, max_length=10)),
                ('team', models.CharField(max_length=30)),
                ('num', models.CharField(max_length=10)),
                ('pos', models.CharField(max_length=10)),
                ('habits', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
                ('birthday', models.CharField(max_length=20)),
                ('debut', models.TextField(blank=True, null=True)),
                ('AQ', models.TextField(blank=True, null=True)),
                ('Country', models.CharField(max_length=20)),
                ('o_name', models.TextField(blank=True, null=True)),
                ('draft', models.TextField(blank=True, null=True)),
                ('retire', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
