# Generated by Django 4.1.5 on 2023-02-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_pitcher_fielder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielder',
            name='BB_K',
        ),
        migrations.AddField(
            model_name='fielder',
            name='FB',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fielder',
            name='GB',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fielder',
            name='SBP',
            field=models.FloatField(default=0.0),
        ),
    ]
