# Generated by Django 4.1.5 on 2023-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0003_remove_fielder_bb_k_fielder_fb_fielder_gb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitcher',
            name='B9',
        ),
        migrations.RemoveField(
            model_name='pitcher',
            name='BA',
        ),
        migrations.RemoveField(
            model_name='pitcher',
            name='H9',
        ),
        migrations.RemoveField(
            model_name='pitcher',
            name='K9',
        ),
        migrations.RemoveField(
            model_name='pitcher',
            name='K_BB',
        ),
        migrations.AddField(
            model_name='pitcher',
            name='BS',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='FB',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='GB',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='NO_BB',
            field=models.SmallIntegerField(default=0),
        ),
    ]
